=== robssson/xlst-transformation/schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="ksiegarnia">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="ksiazka" minOccurs="1" maxOccurs="10000"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="ksiazka">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="nazwa">
        <xs:simpleType>
           <xs:restriction base="xs:string">
           <xs:minLength value="1"/>
           <xs:maxLength value="40"/>
           </xs:restriction>
           </xs:simpleType>
         </xs:element>
        <xs:element name="autor">
        <xs:simpleType>
           <xs:restriction base="xs:string">
           <xs:minLength value="1"/>
           <xs:maxLength value="40"/>
           </xs:restriction>
           </xs:simpleType>
         </xs:element>
        <xs:element name="ilosc_stron">
           <xs:simpleType>
           <xs:restriction base="xs:integer">
           <xs:minInclusive value="5"/>
           <xs:maxInclusive value="2000"/>
           </xs:restriction>
           </xs:simpleType>
         </xs:element>
        <xs:element name="oprawka">
        <xs:simpleType>
        <xs:restriction base="xs:string">
        <xs:enumeration value="miękka"/>
        <xs:enumeration value="twarda"/>
      </xs:restriction>
      </xs:simpleType>
      </xs:element>
        <xs:element name="stan">
        <xs:simpleType>
        <xs:restriction base="xs:string">
        <xs:enumeration value="dostępna"/>
        <xs:enumeration value="brak"/>
      </xs:restriction>
      </xs:simpleType>
      </xs:element>
      </xs:sequence>
      <xs:attribute name="id" type="xs:string" use="required"/>
    </xs:complexType>
  </xs:element>
  </xs:schema>

=== robssson/xlst-transformation/Projekt.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="file:///C:/Users/Tomek/Desktop/ProjektXML/transform.xsl"?>
<?xml-stylesheet type="text/xsl" href="file:///C:/Users/Tomek/Desktop/ProjektXML/transform1.xsl"?>
<ksiegarnia xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:///C:/Users/Tomek/Desktop/ProjektXML/schema.xsd">
  <ksiazka id="1">
  <nazwa>Kamizelka</nazwa>
  <autor>Piotr Morawiecki</autor>
  <ilosc_stron>100</ilosc_stron>
  <oprawka>miękka</oprawka>
  <stan>dostępna</stan>
  </ksiazka>
  <ksiazka id="2">
  <nazwa>Potop</nazwa>
  <autor>Michal Palonek</autor>
  <ilosc_stron>111</ilosc_stron>
  <oprawka>twarda</oprawka>
  <stan>brak</stan>
  </ksiazka>
   <ksiazka id="3">
  <nazwa>Ogniem i mieczem</nazwa>
  <autor>Michal Palonek</autor>
  <ilosc_stron>400</ilosc_stron>
  <oprawka>twarda</oprawka>
  <stan>dostępna</stan>
  </ksiazka>
   <ksiazka id="4">
  <nazwa>Obcy</nazwa>
  <autor>Tomasz Radecki</autor>
  <ilosc_stron>300</ilosc_stron>
  <oprawka>twarda</oprawka>
  <stan>brak</stan>
  </ksiazka>
  <ksiazka id="5">
  <nazwa>Predator</nazwa>
  <autor>Ziomek z tatuażami</autor>
  <ilosc_stron>250</ilosc_stron>
  <oprawka>twarda</oprawka>
  <stan>brak</stan>
  </ksiazka>
  <ksiazka id="6">
  <nazwa>Szklana pułapka</nazwa>
  <autor>Jerzy Dudek</autor>
  <ilosc_stron>250</ilosc_stron>
  <oprawka>twarda</oprawka>
  <stan>dostępna</stan>
  </ksiazka>
  <ksiazka id="7">
  <nazwa>Robocop</nazwa>
  <autor>Janina Morawiecka</autor>
  <ilosc_stron>250</ilosc_stron>
  <oprawka>twarda</oprawka>
  <stan>brak</stan>
  </ksiazka>
  <ksiazka id="8">
  <nazwa>Forest Gump</nazwa>
  <autor>Tom Hanks</autor>
  <ilosc_stron>250</ilosc_stron>
  <oprawka>twarda</oprawka>
  <stan>dostępna</stan>
  </ksiazka>
</ksiegarnia>
